### ISSUE TITLE
svg2cookiecutter.py broken after pull request changes

### ISSUE THREAD

**Issue by halfluck** [arpruss/gcodeplot#11]
I'm unable to run svg2cookiecutter.py after the latest pull request, I get this error

Traceback (most recent call last):
  File "svg2cookiecutter.py", line 223, in <module>
    print(svgToCookieCutter(sys.argv[1]))
  File "svg2cookiecutter.py", line 171, in svgToCookieCutter
    line = Connector('connector'+pathName, points, fill)
  File "svg2cookiecutter.py", line 140, in __init__
    super().__init__(pathName, points, fill, False, None) # no stroke for connectors, thus no use of self.height and self.width
TypeError: super() takes at least 1 argument (0 given)

**Comment by arpruss** [comment]
python 2.x compatibility issue. Fixed.

**Comment by halfluck** [comment]
Working! The new features are AMAZING, so impressed right now.
Do you know if the inside walls has been improved to work?

**Comment by arpruss** [comment]
What was the problem with inside walls?

**Comment by halfluck** [comment]
> What was the problem with inside walls?

'holes' in feature elements within the perimeter of the cookie shape doesn't work with polygon fill
So for example the 'O' and the 'E' in one below

![1](https://user-images.githubusercontent.com/1865731/54861870-841fe400-4d6c-11e9-808f-4d2a60c3a44a.png)

![3](https://user-images.githubusercontent.com/1865731/54861871-884c0180-4d6c-11e9-9a4b-0f594aea934c.jpg)
