### ISSUE TITLE
minFeatureThickness < 1 issues in new release

### ISSUE THREAD

**Issue by halfluck** [arpruss/gcodeplot#12]
testing the new changes and I re exported a SVG I knew worked and I found an issue that has started happening since the new changes,

my setitngs are minFeatureThickness = 0.86;

It ignores that and makes it much much thicker now!

![IMG_20190323_141704](https://user-images.githubusercontent.com/1865731/54862470-753e2f00-4d76-11e9-80de-200fb3733e9e.jpg)

![Untitled](https://user-images.githubusercontent.com/1865731/54862453-209ab400-4d76-11e9-9916-6ec570d87e4a.png)

**Comment by halfluck** [comment]
Old version of program on top and new changes that break the minFeatureThickness < 1 on bottom

**Comment by arpruss** [comment]
Fixed
