### ISSUE TITLE
Cookie Cutter Extension

### ISSUE THREAD

**Issue by alexws54tk** [arpruss/gcodeplot#2]
Hi friend. Thank you, for sharing this work.

Tell me, how to use your **Cookie Cutter** extension?
Reverse engineering of Python and OpenSCAD is too slow by me.

Best regards, alex.

**Comment by arpruss** [comment]
Instructions:
http://www.instructables.com/id/3D-Printable-Cookie-Cutters-With-Inkscape-and-Open/
http://www.thingiverse.com/thing:1943121
