### ISSUE TITLE
ModuleNotFoundError: No module named 'svgpath'

### ISSUE THREAD

**Issue by amiee101** [arpruss/gcodeplot#23]
I am new to Inkscape, and I installed the extension per the instructions, but I get this error, so the file cannot be saved as .scad: 
Traceback (most recent call last):
  File "svg2cookiecutter.py", line 2, in <module>
    import svgpath.parser as parser
ModuleNotFoundError: No module named 'svgpath'

Any ideas?

**Comment by arpruss** [comment]
Did you copy the svgpath folder?

**Comment by amiee101** [comment]
I thought so. I copied it from preferences - the user extensions part. So
it is in there. I even tried uninstalling and reinstalling the earlier
version of Inkscape along with the extensions.
It killed my brain for yesterday. I will be working on it (as I am sure its
user error) today.
Thank you!
Amiee

**Comment by arpruss** [comment]
Also, note that this is not designed for Inkscape 1.x.

**Comment by amiee101** [comment]
That could have been the issue for most of yesterday. Later on, I reverted
to Inkscape 0.92.5 (2060ec1f9f, 2020-04-08) and got the same error, so I
suspect the issue is with my lack of doing something on
the svgpath.parser front.

**Comment by amiee101** [comment]
The issue was that I am, in fact, a moron.
Thanks for responding anyway :) Much appreciated, on both that front, and
for making the extension.

**Comment by arpruss** [comment]
No worries!
