### ISSUE TITLE
SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by LazerPlatypus** [arpruss/gcodeplot#25]
The issue is found in parser.py and gcodeplot.py. using the find & replace tool to replace all occurrences of "is not" with "!=" seems to have resolved the problem, but I have not been able to thoroughly test that this is a good solution and that it does not introduce any more bugs. attached are my modified parser.py and gcodeplot.py files.
[gcodeplot_fix.zip](https://github.com/arpruss/gcodeplot/files/5497719/gcodeplot_fix.zip)

**Comment by arpruss** [comment]
I'm usually pretty careful with these things and think about the difference, so if it's in my code, I wouldn't change it.

**Comment by LazerPlatypus** [comment]
The only reason that I changed it, is because otherwise, the script won't run (it throws that error, and doesn't produce gcode). I would definitely go through and deliberately change what needs to be changed if it was my program, but I'm not familiar with the program, and rarely code in python; thus it got the replace-all treatment.

**Comment by arpruss** [comment]
But that's a warning, not an error.

**Comment by LazerPlatypus** [comment]
I just undid my changes and reran the program. this is the warning screen that pops up:
![image](https://user-images.githubusercontent.com/28767937/98306194-90c47080-1f80-11eb-95f7-dbe7927ac16e.png)
the next bit is a little sporadic:
clicking 'OK' or 'x'-ing out of the window results in this error screen:
![image](https://user-images.githubusercontent.com/28767937/98306426-121c0300-1f81-11eb-8f28-ccf3c48fdfe4.png)
and doesn't produce any gcode.
sometimes, if you try saving it twice, it does work though, still displaying the warning screen, but the error screen doesn't pop up, and gcode is produced. I don't fully understand it.

**Comment by arpruss** [comment]
Ah, I think that's not my code. :-) Try changing just that one is not to !=

**Comment by LazerPlatypus** [comment]
doing that, you get the same warning, but this time in gcodeplot.py on line 456

**Comment by arpruss** [comment]
Can you post your svg file?

**Comment by LazerPlatypus** [comment]
[drawing-2.zip](https://github.com/arpruss/gcodeplot/files/5498309/drawing-2.zip)
