### ISSUE TITLE
No Points error when set to cutting mode, works fine in drawing mode. 

### ISSUE THREAD

**Issue by chilicoke** [arpruss/gcodeplot#6]
I've followed your Instructables hoping to set up a vinyl cutter on my 3D printer, but ran into issue when trying to export/saving gcode. I've tried every setting combination and it it seems like this error only shows up when set to cutting mode, drawing mode exports a gcode file just fine.

Please advise. 
Thanks

**Comment by arpruss** [comment]
I am guessing your drawing doesn't have outlines but only filled regions.

**Comment by chilicoke** [comment]
Yes you are right, it was because region was filled. thank you.
