### ISSUE TITLE
Custom start/end gcodes.

### ISSUE THREAD

**Issue by chilicoke** [arpruss/gcodeplot#7]
Any way to add a field for custom start/end gcodes for those of us converting 3D printers with auto leveling?

Thanks!

**Comment by arpruss** [comment]
Well, you can edit the python code to do that.

**Comment by arpruss** [comment]
It's now supported.

**Comment by chilicoke** [comment]
Woah thank you very much for this! I've just reinstalled the latest version and I don't see any fields to do this, any quick pointers? 

thanks!

**Comment by arpruss** [comment]
It's only there in the command line version, I think.
